### ISSUE TITLE
Add Devlog link to the Forum sidebar

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/jmonkeyengine-website#20]
The Forum sidebar includes a link to the Blog, but not the Devlog, which is apparently a distinct feature. Please add a link to the Devlog.

https://hub.jmonkeyengine.org/t/jmonkeyengine-v3-4-1-release/45160/8

**Comment by stephengold** [comment]
And perhaps also add the link to the Forum nav bar.

**Comment by riccardobl** [comment]
Atm there are 3 tags used as main categories for our posts
- #devlog: development updates
- #communitylog: community updates
- #blog: everything else

Maybe we should use the tag #misc to categorize posts that aren't neither devlogs or communitylogs and then add the blog tag also to the #devlog and #communitylog posts, so that everything is presented when searching for #blog.

Alternatively if we decide to add devlog to the menu, we should add also communitylog, but having so many links might be confusing.

What do you think?

**Comment by stephengold** [comment]
Thanks for explaining the 3 categories of posts.

The rate of new posts is currently about 3 per year, so categorization and filtering aren't needed. Any filtering the reader didn't explicitly request causes confusion and missed posts.

Perhaps the links in the nav bar and sidebar should take the reader to a page that shows all 3 kinds of posts.

**Comment by riccardobl** [comment]
Fixed, the blog tag now includes every blog post, and the generic posts are discerned by the tag misc

**Comment by stephengold** [comment]
Thank you!
